### ISSUE TITLE
Creating links

### ISSUE THREAD

**Issue by valencik** [tomduck/pandoc-fignos#5]
```
"Links are not constructed -- just the figure numbers."
```

Do you have any plans to implement link creation?

Edit: I should mention that this of course works great for TeX as is. But I would love to see it work with HTML outputs as well.

**Comment by tomduck** [comment]
Thanks for your interest, @valencik.  I will look into it implementing this.

**Comment by valencik** [comment]
Thanks!
As another note, [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc) produces nice links in TeX and HTML (it might work in others as well, I haven't tested.)
It would be nice to mimic some of that functionality ultimately.
But unfortunately anything in Haskell is effectively magic to me at this stage, so I have no idea how to figure out their implementation of linking in HTML.

**Comment by tomduck** [comment]
@valencik: I have made the modifications and posted the results to github.  Could you please test to see if it works for you?  If you have `git` then you can install as root using

```
pip install --upgrade git+https://github.com/tomduck/pandoc-fignos.git
```

Otherwise you will need to install from the sources.

I will update the documentation and push out a new version to pypi once we have agreed that everything works.

**Comment by valencik** [comment]
You're a wizard! This works great!
I hope the fix is applicable to [pandoc-eqnos](https://github.com/tomduck/pandoc-eqnos) and [pandoc-tablenos](https://github.com/tomduck/pandoc-tablenos) too.

As a side note: The HTML links link to the figure not the caption. In my mind this is the desired outcome, but it is different from the default in LaTeX. For those looking to get the same effect in LaTeX, I found this to work exactly as desired: http://stackoverflow.com/a/6696146

**Comment by tomduck** [comment]
Excellent.  Thanks for the suggestion for html links -- and also for the latex tip; very cool!

_pandoc-fignos_ version 0.4 has been pushed out to pipy.

I will update pandoc-eqnos and pandoc-tablenos in the next few days.

Cheers!

**Comment by valencik** [comment]
The current version on PyPI appears broken:

``` bash
$: pip install pandoc-fignos
$: wget https://raw.githubusercontent.com/tomduck/pandoc-fignos/master/demos/demo.md
$: pandoc --filter pandoc-fignos demo.md -o demo.tex
pandoc: not enough input
```

But installing straight from the GitHub repo appears fine.

``` bash
$: pip install --upgrade git+https://github.com/tomduck/pandoc-fignos.git
$: pandoc --filter pandoc-fignos demo.md -o demo.tex
```

This currently affects [pandoc-tablenos](https://github.com/tomduck/pandoc-tablenos) and [pandoc-eqnos](https://github.com/tomduck/pandoc-eqnos) on PyPI as well.

**Comment by tomduck** [comment]
I don't seem to have this issue.  Can you try installing again using the --upgrade flag?  Also, do you have the images in place for the demo?

Note that I haven't updated pandoc-tablenos yet.

I'm re-opening this issue until we are sure everything is working.

**Comment by tomduck** [comment]
I just pushed the html links update for pandoc-tablenos to github, but will hold off on pypi for now.

**Comment by valencik** [comment]
It might be a weird pip caching issue? You can see the [strange behaviour in this short screencast.](http://gfycat.com/ShowyForcefulInganue)
What's weird is I can replicate this time and time again.

After `pip uninstall pandoc-fignos` I don't see anything resembling `pandoc-fignos` hanging around in `site-packages` or `pip list`. And trying to uninstall again produces the expected:

```
Cannot uninstall requirement pandoc-fignos, not installed
```

I must be missing something here...

Edit: No, I do not have the images in place, but as you'll note that appears to be no problem if I install `pandoc-fignos` from git directly.

**Comment by tomduck** [comment]
Hi @valencik.  Is this still an issue?  I'm not sure if we resolved it or not.  Thanks.

**Comment by valencik** [comment]
Hi @tomduck, yes I still have the same issue. And can reproduce as described above.

I just downloaded pandoc_fignos.py from pypi and from master branch on github and they do differ:

```
132c132
<         if fmt in ('html', 'html5'):
---
>         if fmt == 'html' or fmt == 'html5':
163c163
<         elif fmt in ('html', 'html5'):
---
>         elif fmt == 'html' or fmt == 'html5':
```

The pypi version is from commit: 7260a594a0c3b2680ae665371e57aeac029adc9d

**Comment by tomduck** [comment]
I don't think those changes should have any effect.  In any case, I just finished some other bug fixes, and so expect to post a new version to pypi in the very near future.  Stay tuned, and thanks for your patience.

**Comment by tomduck** [comment]
I just posted pandoc-fignos 0.5 to pypi.  Does it have the same issue?  Thanks.

**Comment by valencik** [comment]
Unfortunately I still am.
Using this [demo.md](https://raw.githubusercontent.com/tomduck/pandoc-fignos/master/demos/demo.md)
<img width="670" alt="pandoc-fignos-issue" src="https://cloud.githubusercontent.com/assets/5440389/12066838/b085556e-afc4-11e5-9abb-b856a01b023f.png">

**Comment by valencik** [comment]
Just tried the same procedure on a Ubuntu VM and I could not replicate the issue.
Perhaps this is a one off issue with my current setup on OS X and we should close the issue.

The long and short of it is that I can continue to use your filters by installing them from github.
I am fine with this. In fact it is what I have been doing for months and how I did it for marking up my thesis.
Thank you. I appreciate your patience and contributions.

**Comment by tomduck** [comment]
It's great to hear that the filter was useful for thesis writing!

Note: The same error message

```
pandoc: Error in $: not enough input
```

is being [reported](https://github.com/tomduck/pandoc-eqnos/issues/4) for pandoc-eqnos under Arch linux.  I'm testing using OS X El Capitan and on occasion using Debian.

So, let's keep this open for now.

**Comment by tomduck** [comment]
I have posted pandoc-fignos 0.6 to pypi.  Could you please see if it works for you? @anntzer showed in [pandoc-eqnos Issue #4](https://github.com/tomduck/pandoc-eqnos/issues/4) that flushing stdout before exiting solves the problem.

**Comment by valencik** [comment]
IT WORKS!
<img width="715" alt="pip-pandoc-fignos-works" src="https://cloud.githubusercontent.com/assets/5440389/12072574/84e4cc12-b0bb-11e5-9096-e8dec9ca7555.png">

**Comment by tomduck** [comment]
Yay!  Thanks so much for the feedback.  :o)
